# Generated by Django 4.0 on 2022-11-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Submitted'), (2, 'Ongoing'), (3, 'Received')], default=1),
        ),
    ]
